import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Adaptive launcher icon invariants — Phase 5 task 5.3.
///
/// Generated by `flutter_launcher_icons` from sources at
/// `assets/branding/`. The generator runs once at icon-design time
/// (re-run `python3 tools/generate_icon.py && dart run
/// flutter_launcher_icons` to regenerate). These invariants catch a
/// future commit that accidentally deletes the generated assets,
/// drops the manifest icon attribute, or breaks the adaptive
/// foreground/background wiring.
///
/// Like `android_manifest_test.dart` (DECISIONS row 33), this is a
/// platform-level regression check that `flutter analyze` and
/// `flutter test` would otherwise miss — adaptive icon problems only
/// surface as a wrong-looking launcher icon at install time.
void main() {
  String readFile(String relPath) {
    final f = File('${Directory.current.path}/$relPath');
    expect(f.existsSync(), isTrue, reason: '$relPath must exist');
    return f.readAsStringSync();
  }

  bool fileExists(String relPath) =>
      File('${Directory.current.path}/$relPath').existsSync();

  group('source assets (regenerable via tools/generate_icon.py)', () {
    test('icon-foreground.png is the canonical adaptive foreground source',
        () {
      expect(fileExists('assets/branding/icon-foreground.png'), isTrue);
    });

    test('icon-legacy.png is the composited pre-API-26 fallback source', () {
      expect(fileExists('assets/branding/icon-legacy.png'), isTrue);
    });

    test('generator script is committed for reproducibility', () {
      expect(fileExists('tools/generate_icon.py'), isTrue);
    });
  });

  group('adaptive icon descriptor (Android 8.0+, API 26+)', () {
    late String adaptiveXml;

    setUpAll(() {
      adaptiveXml = readFile(
        'android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml',
      );
    });

    test('adaptive-icon root element is present', () {
      expect(adaptiveXml, contains('<adaptive-icon'));
    });

    test('foreground references the generated drawable', () {
      expect(adaptiveXml, contains('@drawable/ic_launcher_foreground'));
    });

    test('background references the warm off-white color resource', () {
      expect(adaptiveXml, contains('@color/ic_launcher_background'));
    });
  });

  group('background color (DECISIONS row 35: warm off-white #F7F5F2)', () {
    test('colors.xml defines ic_launcher_background as #F7F5F2', () {
      final colors = readFile('android/app/src/main/res/values/colors.xml');
      expect(colors, contains('ic_launcher_background'));
      // Case-insensitive match — Android XML conventions vary on hex
      // capitalization across tools.
      expect(colors.toLowerCase(), contains('#f7f5f2'));
    });
  });

  group('per-density assets exist', () {
    const densities = ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi'];

    for (final d in densities) {
      test('mipmap-$d/ic_launcher.png (legacy launcher icon)', () {
        expect(
          fileExists('android/app/src/main/res/mipmap-$d/ic_launcher.png'),
          isTrue,
        );
      });

      test('drawable-$d/ic_launcher_foreground.png (adaptive foreground)', () {
        expect(
          fileExists(
            'android/app/src/main/res/drawable-$d/ic_launcher_foreground.png',
          ),
          isTrue,
        );
      });
    }
  });

  group('AndroidManifest references the launcher icon', () {
    test('android:icon points at @mipmap/ic_launcher', () {
      final manifest = readFile('android/app/src/main/AndroidManifest.xml');
      expect(manifest, contains('android:icon="@mipmap/ic_launcher"'));
    });
  });
}
