import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Splash screen invariants — Phase 5 task 5.4.
///
/// Generated by `flutter_native_splash` from the config block at the
/// bottom of pubspec.yaml. The honest-dark-mirror treatment (locked
/// by user choice in task 5.4) means we ship two backgrounds and two
/// foreground variants — light splash on warm off-white (#F7F5F2)
/// with the graphite mark, dark splash on warm graphite (#1F1E1C)
/// with the warm-off-white mark.
///
/// Like the launcher_icon_test (and the manifest invariants test —
/// DECISIONS row 33), these checks catch regressions that
/// `flutter analyze` and `flutter test` would otherwise miss: a
/// future commit that drops one of the generated drawables, edits
/// styles.xml in a way that breaks the Android-12 system splash
/// wiring, or removes the LaunchTheme reference in AndroidManifest.
///
/// To regenerate after changing the brand colors or marks:
///   python3 tools/generate_icon.py
///   dart run flutter_native_splash:create
void main() {
  String readFile(String relPath) {
    final f = File('${Directory.current.path}/$relPath');
    expect(f.existsSync(), isTrue, reason: '$relPath must exist');
    return f.readAsStringSync();
  }

  bool fileExists(String relPath) =>
      File('${Directory.current.path}/$relPath').existsSync();

  group('source assets (regenerable via tools/generate_icon.py)', () {
    test('icon-foreground-dark.png is the dark-splash mark source', () {
      expect(fileExists('assets/branding/icon-foreground-dark.png'), isTrue);
    });
  });

  group('per-density splash assets exist', () {
    const densities = ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi'];

    for (final d in densities) {
      // Pre-Android-12 (legacy) splash bitmap — light + dark.
      test('drawable-$d/splash.png (light, pre-Android-12)', () {
        expect(
          fileExists('android/app/src/main/res/drawable-$d/splash.png'),
          isTrue,
        );
      });
      test('drawable-night-$d/splash.png (dark, pre-Android-12)', () {
        expect(
          fileExists(
              'android/app/src/main/res/drawable-night-$d/splash.png'),
          isTrue,
        );
      });

      // Android-12+ system splash bitmap — light + dark.
      test('drawable-$d/android12splash.png (light, Android 12+)', () {
        expect(
          fileExists(
              'android/app/src/main/res/drawable-$d/android12splash.png'),
          isTrue,
        );
      });
      test('drawable-night-$d/android12splash.png (dark, Android 12+)', () {
        expect(
          fileExists(
            'android/app/src/main/res/drawable-night-$d/android12splash.png',
          ),
          isTrue,
        );
      });
    }
  });

  group('launch_background drawable layer-list (pre-Android-12)', () {
    test('drawable/launch_background.xml exists and references splash', () {
      final xml =
          readFile('android/app/src/main/res/drawable/launch_background.xml');
      expect(xml, contains('@drawable/background'));
      expect(xml, contains('@drawable/splash'));
    });

    test('drawable-night/launch_background.xml mirrors the layer-list', () {
      final xml = readFile(
        'android/app/src/main/res/drawable-night/launch_background.xml',
      );
      expect(xml, contains('@drawable/background'));
      expect(xml, contains('@drawable/splash'));
    });
  });

  group('Android 12+ splash theme (windowSplashScreen* attributes)', () {
    test('values-v31/styles.xml binds light splash to warm off-white', () {
      final styles =
          readFile('android/app/src/main/res/values-v31/styles.xml');
      expect(styles, contains('windowSplashScreenBackground'));
      // Background color matches the design-system warm off-white
      // (DECISIONS row 35, PetPalColors.warmOffWhite).
      expect(styles.toLowerCase(), contains('#f7f5f2'));
      expect(styles, contains('@drawable/android12splash'));
    });

    test('values-night-v31/styles.xml binds dark splash to warm graphite',
        () {
      final styles = readFile(
        'android/app/src/main/res/values-night-v31/styles.xml',
      );
      expect(styles, contains('windowSplashScreenBackground'));
      // Dark background matches darkSurfaceLow from the Phase 5
      // token palette.
      expect(styles.toLowerCase(), contains('#1f1e1c'));
      expect(styles, contains('@drawable/android12splash'));
    });
  });

  group('LaunchTheme wiring in pre-Android-12 styles.xml', () {
    test('values/styles.xml routes LaunchTheme to launch_background', () {
      final styles = readFile('android/app/src/main/res/values/styles.xml');
      expect(styles, contains('LaunchTheme'));
      expect(styles, contains('@drawable/launch_background'));
    });

    test('values-night/styles.xml mirrors the LaunchTheme route', () {
      final styles =
          readFile('android/app/src/main/res/values-night/styles.xml');
      expect(styles, contains('LaunchTheme'));
      expect(styles, contains('@drawable/launch_background'));
    });
  });

  group('AndroidManifest applies LaunchTheme to the launcher activity', () {
    test('android:theme="@style/LaunchTheme"', () {
      final manifest =
          readFile('android/app/src/main/AndroidManifest.xml');
      expect(manifest, contains('android:theme="@style/LaunchTheme"'));
    });
  });
}
