/// Coverage fixture for the red-flag screener (CLAUDE.md §10 + DECISIONS
/// row 29). Each category ships ≥30 positive phrasings + ≥20 negative
/// phrasings here; the parameterised test in
/// `red_flags_fixture_test.dart` walks every entry. New patterns
/// require new fixtures in the same commit (DECISIONS row 29 coverage
/// rule).
///
/// Built incrementally across multiple commits — one or two
/// categories per commit — to keep diffs reviewable and the
/// regression surface honest. Categories are added in the canonical
/// order from `lib/harness/guardrails/red_flags.dart`.
library;

/// Phrases that MUST flag the named category.
const positives = <String, List<String>>{
  'blood_in_stool': [
    'I noticed blood in his stool this morning',
    'There was blood in her stool',
    'Blood in the stool again',
    'Blood in his poop overnight',
    'Bloody stool today',
    'Bloody diarrhea twice today',
    'Bloody diarrhoea — really worried',
    'There is blood in his diarrhea this morning',
    'Found blood in her diarrhoea',
    'Saw blood in his feces',
    'Blood in his faeces',
    'Loki passed bloody poop',
    'Loki passed a bloody stool',
    'There is blood in the diarrhea',
    'Blood in the poop, second time',
    'His stool is black',
    'Her stool is dark',
    'Stool is tarry',
    'Stool looks black',
    'Stool looks tarry',
    'His stool looks dark and sticky',
    'Her poop is black',
    'Poop is bloody',
    'Poop seems red',
    'Faeces appear black',
    'Black diarrhea',
    'Tarry stool today',
    'Red stool, no idea why',
    'Dark stool, like coffee grounds',
    'Loki has melena',
    'Suspect melena',
  ],
  'blood_in_vomit': [
    'There was blood in his vomit',
    'Blood in her vomit twice',
    'Blood in the vomit this morning',
    'She vomited blood last night',
    'He vomited blood right before bed',
    'Loki vomited blood',
    'Threw up blood',
    'Threw up blood twice in an hour',
    'Throwing up blood',
    'He throws up blood after meals',
    "She's been throwing up blood",
    'Throw up blood — vet now?',
    'Coughing up blood',
    'Loki is coughing up blood',
    'He started coughing up blood',
    'Hematemesis since yesterday',
    'Possible hematemesis',
    'Blood in his throw up',
    'Blood in her throw-up',
    'Blood in her puke',
    'Blood in his puke',
    'Vomits blood every few hours',
    'Vomited blood overnight',
    'There is blood in his vomit on the rug',
    'Found blood in the vomit',
    'Saw blood in her vomit',
    'Blood in throw up — second time',
    'He threw up blood after dinner',
    'She vomited blood and bile',
    'Vomits blood-tinged liquid',
    'He has been vomiting blood',
  ],
  'repeat_vomit': [
    'Vomited 5 times today',
    'Vomited 6 times in the last few hours',
    'Vomited 4 times since lunch',
    'Vomited 10 times overnight',
    'Vomited several times this morning',
    'Vomited several times since breakfast',
    'Vomited many times over the weekend',
    'Vomited multiple times today',
    'Vomited repeatedly all afternoon',
    'Vomited all day',
    'Vomited all morning',
    'Vomited all night',
    'Vomited all afternoon',
    'Threw up 3 times in an hour',
    'Threw up 4 times today',
    'Threw up several times today',
    'Threw up many times in the last hour',
    'Threw up multiple times since dinner',
    'Threw up repeatedly this evening',
    'Throwing up several times an hour',
    'Throwing up multiple times today',
    'Throwing up all day',
    'Throwing up all morning',
    'Throwing up all night',
    'Throwing up all afternoon',
    'Keeps throwing up every twenty minutes',
    'Keeps throwing up no matter what we do',
    'Keeps vomiting since this morning',
    "Can't stop throwing up",
    'Cannot stop vomiting',
    "He can't stop vomiting since lunch",
  ],
  'seizure': [
    'Loki had a seizure',
    'Loki had a seizure last night',
    'Loki had a small seizure this morning',
    'Loki had her first seizure',
    'She had a seizure for about a minute',
    'He had two seizures today',
    'Three seizures this week',
    'Multiple seizures in 24 hours',
    'Seizures are getting more frequent',
    'She was seizing for about a minute',
    'He was seizing on the couch',
    'Loki was seizing when I came home',
    'Seizing for about thirty seconds',
    'Seized for two minutes straight',
    'A convulsion just now',
    'A convulsion that lasted a minute',
    'Two convulsions in an hour',
    'He is convulsing right now',
    'She is convulsing on the floor',
    'Loki is convulsing — what do we do',
    'Convulsed for thirty seconds',
    'Convulsed twice this week',
    'Loki convulses sometimes after eating',
    'Loki had a fit yesterday',
    'He had a fit on the walk',
    'She had a fit this morning',
    'Epileptic episode at 3am',
    'An epileptic fit',
    'An epileptic attack',
    'She had an epileptic fit',
    'Possible seizure activity',
  ],
  'bloat': [
    'His belly looks distended',
    'Her belly looks distended',
    'His belly looks bloated',
    'Her belly looks bloated',
    'His belly looks swollen',
    'His belly looks hard',
    'His belly looks tight',
    'His abdomen is bloated and hard',
    'His abdomen is distended',
    'Her abdomen is swollen',
    'Her abdomen feels tight',
    'His stomach is bloated',
    'His stomach feels hard',
    'His stomach looks distended',
    'Her stomach is swollen this morning',
    'His tummy looks bloated',
    'Her tummy looks distended',
    'His tummy is hard to the touch',
    'Bloated abdomen since dinner',
    'Distended abdomen — really worried',
    'Swollen belly',
    'Hard belly all of a sudden',
    'Tight belly, tense to the touch',
    'A bloated stomach after his meal',
    'A distended stomach',
    'A swollen stomach',
    'A hard stomach',
    'Possible GDV',
    'Suspected GDV',
    'Worried about GDV',
    'Vet says possible gastric dilatation',
  ],
  'toxin_ingestion': [
    'He ate chocolate',
    'She ate chocolate from the counter',
    'He ate cocoa powder',
    'She ate grapes',
    'He ate raisins',
    'Loki ate raisins from the counter',
    'She ate onion',
    'He ate onions from the trash',
    'She ate garlic',
    'He ate chives',
    'Mochi ate a leek',
    'She ate xylitol gum',
    'He ate sugar-free gum',
    'She ate gum off the floor',
    'Loki ate sweetener — pure xylitol',
    'He ate a lily',
    'Mochi ate lilies from the bouquet',
    'She ate a tulip',
    'He ate daffodils',
    'Drank antifreeze in the garage',
    'Drank coolant',
    'Drank cleaner',
    'Drank bleach somehow',
    'Drank pool chemicals',
    'He ate rat poison',
    'She ate rodenticide',
    'He ate slug pellets in the garden',
    'She ate Tylenol off the counter',
    'He ate Advil from a dropped bottle',
    'She ate ibuprofen',
    'He ate paracetamol',
    'She ate aspirin',
    'He ate naproxen',
    'She ate marijuana edibles',
    'He ate weed',
    'She ate cannabis edibles',
    'He ate edibles',
    'She ate mushrooms in the yard',
    'He ate a toadstool',
    'Got into the trash',
    'He got into the garbage',
    'She got into the bin overnight',
    'Swallowed a sock',
    'He swallowed a string',
    'She swallowed a coin',
    'He swallowed a battery',
    'She swallowed a button battery',
    'He swallowed a magnet',
    'She swallowed a hair tie',
    'He swallowed a fishhook',
    'I think Loki was poisoned',
    'Possibly poisoned at the park',
    'Suspect she was poisoned',
  ],
  'dyspnea': [
    'Laboured breathing',
    'Labored breathing for the last hour',
    'She has trouble breathing',
    'He has trouble breathing',
    'Difficulty breathing since the walk',
    'Hard breathing all day',
    'Hard to breathe',
    'Struggling to breathe',
    "He can't breathe",
    "She can't breathe right now",
    'Cannot breathe',
    'Gasping for air',
    'Gasping for breath',
    'He is gasping for air',
    'She is gasping for breath',
    'Open-mouth breathing',
    'Open mouth breathing in my cat',
    'Open-mouth breathing — cat emergency?',
    'Cyanotic-looking after exertion',
    'Cyanotic gums and lips',
    'Blue tongue',
    'Purple tongue this morning',
    'Wheezing badly tonight',
    'Wheezing severely',
    'Wheezing hard since dinner',
    "Loki's breathing is laboured",
    "Mochi's breathing is laboured",
    'She is having trouble breathing',
    'He is having difficulty breathing',
    'Has trouble breathing while sleeping',
    'Open-mouth panting in a cat',
  ],
  'collapse': [
    'He collapsed in the yard',
    'She collapsed during the walk',
    'Loki collapsed on the kitchen floor',
    'Mochi collapsed at the dog park',
    'Just collapsed for no reason',
    'Collapses every now and then',
    'Collapsed twice today',
    'He passed out',
    'She passed out for a few seconds',
    'Loki passed out after running',
    'She passed out and came back',
    'Lost consciousness briefly',
    'He lost consciousness for a minute',
    'She lost consciousness on the stairs',
    'Loki lost consciousness — really worried',
    'Unconscious on the floor',
    'He is unconscious',
    'She is unconscious right now',
    'Unresponsive when I came home',
    'Loki is unresponsive',
    'She is non-responsive',
    'He is non responsive',
    'Loki fainted',
    'She fainted briefly',
    'He fainted on the walk',
    "He won't wake up",
    "She won't wake up",
    "Loki won't wake up",
    "She won't come to",
    "He won't respond at all",
    "Won't respond to his name or treats",
  ],
  'lethargy_anorexia': [
    "Loki seems lethargic and won't eat anything",
    "She's lethargic and won't eat",
    "He's lethargic and not eating",
    'She is listless and refusing food',
    'He is listless and not eating',
    "Loki is listless and won't eat",
    "She is exhausted and won't eat",
    "He's been exhausted and refusing food",
    'Lethargic and no appetite',
    'Listless and no appetite',
    'Exhausted and no appetite',
    'Very tired and not eating',
    'Very tired and refusing food',
    'Extremely tired and not eating',
    'Extremely tired and no appetite',
    "Won't get up and won't eat",
    "Won't move and refusing food",
    "Won't stand and not eating",
    "Won't come out and not eating",
    'Lethargic and refuses to eat',
    'Listless and refuses to eat',
    "He's lethargic and hasn't eaten",
    "She's listless and hasn't eaten",
    'Lethargic with anorexia',
    'Listless with anorexia',
    'Lethargic and anorexic',
    'Listless and anorexic',
    'Very tired and refusing food today',
    'Very tired and refused to eat dinner',
    "She won't move and won't eat",
    "He won't stand up and won't eat his food",
  ],
  'trauma_fracture': [
    'Broken leg from a fall',
    'Suspect a broken bone',
    'Possible broken paw',
    'Broken paw on the back leg',
    'Broken tail from the door',
    'Broken jaw, vet appointment booked',
    'Broken rib — really worried',
    'Broken hip after the slip',
    'Fractured leg',
    'Suspected fracture in the front leg',
    'Fractures in the paw',
    'Fractured rib',
    'Fracturing — vet says yes',
    "Won't put weight on his back leg",
    "Won't put weight on her front paw",
    "Won't put weight on the right side",
    'Hit by a car this morning',
    'Hit by a truck',
    'Hit by a bike',
    'Hit by a vehicle',
    'Hit by a bicycle on the path',
    'Run over by a car',
    'Struck by a car',
    'Hit by a car — bleeding',
    'Fell from the balcony',
    'Fell off the bed and yelped',
    'Fell down the stairs',
    'Attacked by a dog',
    'Attacked by a coyote in the yard',
    'Attacked by a wild animal',
    'Deep wound on his leg',
    'Deep cut on her paw',
    'Deep laceration on the side',
    'Deep gash from a fence',
    "Won't stop bleeding",
    "Won't stop bleeding — calling vet",
  ],
  'pale_gums': [
    'His gums are pale',
    'Her gums are pale',
    'His gums look pale',
    'Her gums look pale',
    'His gums seem pale today',
    'Her gums seem pale',
    'His gums are white',
    'Her gums look white',
    'White gums this morning',
    'Whitish gums',
    "Loki's gums are whitish",
    'His gums are grey',
    'His gums look grey',
    'Her gums look gray',
    'Grey gums today',
    'Gray gums — worried',
    'His gums are blue',
    'Her gums look blue',
    'Bluish gums after exertion',
    'His gums are bluish',
    'His gums look bluish',
    'His gums are yellow',
    'Yellow gums noticed today',
    'Her gums look yellow',
    'His gums are yellowish',
    "Loki's gums look pale and clammy",
    "Mochi's gums seem pale this morning",
    'Pale gums when I checked',
    'Pale gums and lethargy',
    'Pale gums noticed at the vet',
    'Pale gums — calling the vet',
  ],
};

/// Phrases that MUST NOT flag the named category. These are
/// deliberately textually adjacent to the positive set — the
/// false-positive-tolerant principle (DECISIONS row 29) means we
/// allow some over-matching, but we still want the obvious adversarial
/// cases (e.g. "chocolate-coloured fur") to stay clean.
const negatives = <String, List<String>>{
  'blood_in_stool': [
    'His stool was brown and normal',
    'Normal stool today',
    'Loki had a great walk and a normal poop',
    'Stool sample at the vet went fine',
    'No blood, no diarrhea, all good',
    'Reading a book about blood lineages in dogs',
    'The trainer talks about blood-tracking dogs',
    'Bought a poop bag at the store',
    'Brown poop, firm, healthy',
    'Asked the vet about stool consistency',
    'No issues with his stool this week',
    'She had a tiny scratch but no bleeding',
    'Stool looks brown and firm',
    'Stool consistency improved',
    'Diarrhoea cleared up overnight, no blood',
    'No blood at all in his poop',
    'Vet asked us to bring a stool sample',
    'Loki licked some red paint earlier',
    'Just a stain on the rug — not blood',
    'Reddish carpet, not stool',
  ],
  'blood_in_vomit': [
    'He vomited once after eating grass',
    'Threw up some hair, looked normal',
    'Vomited bile this morning',
    'She vomited foam',
    'Loki vomited a chew toy',
    'No blood in any of his vomit',
    'The vomit looked yellow',
    'Vomit was clear liquid',
    'Threw up his food whole',
    "Loki's blood test came back fine",
    "We're going for a blood draw next week",
    'Coughed twice but no blood',
    'Coughing — vet says kennel cough',
    'Reading about blood types in cats',
    'Brought a vomit sample to the vet',
    'Blood pressure check next week',
    'Donated blood for a transfusion drive',
    'Watching Bloodhound rescue videos',
    'No blood, no concern',
    'The puke was clear and small',
  ],
  'repeat_vomit': [
    'Vomited once after eating grass',
    'He threw up his food once',
    'She threw up a hairball',
    'Threw up bile in the morning',
    'Loki vomited a chew toy',
    'A single throw-up after the car ride',
    'Threw up on the carpet but only once',
    'Vomited on the rug, just one time',
    'No vomiting today',
    'Hasn\'t thrown up at all',
    'No more vomiting since yesterday',
    'Vomiting stopped after the meds',
    'Threw up his treat — seems fine now',
    'He vomits occasionally after fast eating',
    'Loki rarely vomits',
    'One small throw-up, otherwise normal',
    'A bit of nausea but no actual vomit',
    'She gagged but did not vomit',
    'Was about to throw up but held it',
    'No real vomiting, just retching',
  ],
  'seizure': [
    'Loki had a great walk on the beach',
    'A little twitchy when sleeping',
    'The puppy had a tantrum',
    'A small shudder, then napped',
    'Loki had a temper tantrum at the dog park',
    'Watching a documentary about service dogs',
    'Vet ruled out anything neurological',
    'A bit jumpy at the door',
    'Spasming his tail in excitement',
    'Tail thumping wildly when she sees me',
    'Got the zoomies after dinner',
    'Trembling a little in the cold',
    'Shaking off water after the bath',
    'She always shakes when she meets new dogs',
    'Trembled briefly during the fireworks',
    'Quivering with anticipation for treats',
    'Did a little dance before food',
    'Had a tantrum about the harness',
    'Threw a fit because I left the room',
    'Was wriggling all over after his walk',
  ],
  'bloat': [
    'His belly is round but soft',
    'Her belly is full from dinner',
    'A bit of a tummy after lunch',
    'Pleasantly plump puppy',
    'Round little belly, otherwise normal',
    'Full belly, sleeping it off',
    'Soft tummy when she rolls over',
    'Loved a belly rub today',
    'Got a belly rub at the park',
    'His belly fur is matted',
    'Tummy itch from the new shampoo',
    'A belly band on the puppy',
    'His belly is soft and warm',
    'No bloating, no distension',
    'Her belly is fine, just a bit fluffy',
    'Stomach upset for a day, normal now',
    'Stomach grumbling before dinner',
    'Stomach a little gassy',
    'Belly is fine',
    'Belly band fits well',
  ],
  'pale_gums': [
    'Her gums look pink and healthy',
    'Pink gums — vet was happy',
    'Healthy pink gums at the checkup',
    'Gums are a healthy pink',
    "Loki's gums are pink",
    'Mochi has pink gums today',
    'Pink and moist gums',
    'Gums look great this week',
    'Vet checked the gums — all good',
    'Gum line looks healthy',
    "We're switching gum-care chews",
    'New gum-protective dental treats',
    'Bought a chew toy at the store',
    "Dog's gums and teeth look fine",
    'Gum-tissue check at next visit',
    'Healthy gum colour reported',
    'Gums look normal',
    'Gums look good',
    'Gums are normal pink',
    'Pink gums is the right colour',
  ],
  'toxin_ingestion': [
    'He ate chicken for dinner',
    'She ate kibble as usual',
    'Ate a few blueberries on a walk',
    'He ate a carrot',
    'She ate a sweet potato chew',
    'Ate a bit of apple core (no seeds)',
    'He ate a piece of cheese',
    'She ate her dental treat',
    'Ate his prescription food',
    'Ate a frozen Kong',
    'Ate a bully stick',
    'Drank water from his bowl',
    'Drank from the dog fountain',
    'Drank a lot of water after the walk',
    'Found a candy wrapper in the trash, no candy',
    'Threw away an old chocolate bar (in a sealed bin)',
    'Cleaning supplies are locked up',
    'Anti-freeze stays in the locked shed',
    'No access to the garbage now',
    'New garbage can with a lid',
  ],
  'dyspnea': [
    'Loki was breathing heavily after running',
    'Heavy breathing on a hot day',
    'A bit of panting on the walk',
    'Panting normally after the dog park',
    'Light panting at home',
    'Snoring loudly while asleep',
    'Snores like an old man',
    'Slept on his back, snoring',
    'Took a deep breath and yawned',
    'Yawned and stretched',
    'Sighed before settling down',
    'Quiet breathing while sleeping',
    'Steady breathing all night',
    'No wheezing, no struggle',
    'Fine after a short rest',
    'Caught his breath quickly',
    'Took a few breaths and was fine',
    'Breathing slowed after rest',
    'Calm breathing all evening',
    'Heart-rate normal, breathing normal',
  ],
  'collapse': [
    'A long nap on the couch',
    'Snoozing in the sun',
    'Fell asleep on my lap',
    'Quiet morning, just resting',
    'Slept through the storm',
    'Resting after a long walk',
    'Lounging by the window',
    'Curled up on the rug',
    'Took a long nap after lunch',
    'Just lazing around',
    'Sunbathing on the porch',
    'Snoring lightly in his crate',
    'Out cold in the warm spot',
    'Knocked out from running',
    'Worn out but happy',
    'Tired after the dog park',
    'A bit tired this evening',
    'Calm and resting',
    'Relaxed and dozing',
    'Dozed off after dinner',
  ],
  'trauma_fracture': [
    'He broke into the treat jar again',
    'Broke his record for fastest fetch',
    'Broke a chew toy in half',
    'Broke the leash today, oops',
    'Cracked the bowl by knocking it',
    'A small scratch from a thorn',
    'A tiny cut on his pad',
    'Slipped but recovered',
    'Tripped over a root, walked it off',
    'Tumbled briefly, no harm done',
    'A little stumble on the rug',
    'Limping a bit from a thorn',
    'Light limp, then walked it off',
    'Sore paw pad from concrete',
    'A grazed pad after the long walk',
    'Bumped into the door frame',
    'Pulled on the leash hard',
    'A small scrape, cleaned and dressed',
    'Took a short tumble, all good',
    'Bruised toenail from a slip',
  ],
  'lethargy_anorexia': [
    'Loki is a bit lethargic today',
    'She is lethargic but eating fine',
    'A little listless but eating well',
    "He's tired but eats normally",
    "She's exhausted from the dog park",
    "She won't eat her dinner",
    'Refused food once, ate later',
    "He won't eat the new kibble but eats treats",
    'Skipped breakfast, ate lunch',
    'No appetite for the new food, fine with old',
    'Lethargic in the heat — drinking water normally',
    'Listless after the bath, ate dinner anyway',
    'Tired but bouncy after a nap',
    'Loved his dinner, sleepy after',
    'Not eating the kibble — picky',
    'Refusing food because of the new bowl',
    'Hasn\'t eaten since I switched brands',
    'Eating slowly today',
    'Eating less than usual but lively',
    "She's lethargic this evening — ate well at lunch",
  ],
};
